New1\TechTalkBundle\Entity\Comment:
    type: entity
    table: comment
    id:
        id:
            type: integer
            generator: {strategy: AUTO }
    fields:
        comment:
            type: string
            length: 255
    manyToOne:
        post:
            targetEntity: Post
            inversedBy: comments
            joinColumn:
                name: post_id
                referencedColumnName: id
