New1\TechTalkBundle\Entity\Post:
    type: entity
    table: post
    id:
        id:
            type: integer
            generator: {strategy: AUTO }
    fields:
        title: 
            type: string
            length: 255
        content:
            type: string
            length: 255
    oneToMany:
        comments:
            targetEntity: Comment
            mappedBy: post
    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: posts
            joinTable:
              name: tag_post
              joinColumns:
                post_id:
                  referencedColumnName: id
              inverseJoinColumns:
                tag_id:
                  referencedColumnName: id
