new1_tech_talk:
    resource: "@New1TechTalkBundle/Resources/config/routing.yml"
    prefix:   /

test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
login:
    path:     /login
    defaults: { _controller: TestBundle:Security:login }
